<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use App\Enums\LoanRevisionStatus;

class LoanRevision extends Model
{
    use HasFactory;

    protected $fillable = [
        'loan_application_id',
        'revision_no',
        'revision_type',
        'status',
        'previous_outstanding_amount',
        'previous_term',
        'previous_installment_amount',
        'revised_outstanding_amount',
        'revised_term',
        'revised_installment_amount',
        'reason',
        'document',
        'remarks',
        'requested_by',
        'approved_by',
        'approved_at',
        'effective_date',
    ];

    // created_at stays visible: it is when the revision was requested, and
    // nothing else records that. The revision list prints it in its Created
    // column and the detail page opens its approval timeline with it, so
    // hiding it left both blank -- the timeline card rendered with no rows at
    // all while the revision was still pending, since approved_at is null then
    // too.
    protected $hidden = [
        'updated_at',
        'deleted_at',
    ];

    protected $appends = [
        'document_url',
    ];

    protected $casts = [
        'loan_application_id'          => 'integer',
        'revision_no'                  => 'integer',
        'status'                       => LoanRevisionStatus::class,
        'previous_outstanding_amount'  => 'decimal:2',
        'previous_term'                => 'integer',
        'previous_installment_amount'  => 'decimal:2',
        'revised_outstanding_amount'   => 'decimal:2',
        'revised_term'                 => 'integer',
        'revised_installment_amount'   => 'decimal:2',
        'requested_by'                 => 'integer',
        'approved_by'                  => 'integer',
        'approved_at'                  => 'datetime',
        'effective_date'               => 'date',
    ];

    /**
     * Relationship with the parent LoanApplication.
     */
    public function loanApplication(): BelongsTo
    {
        return $this->belongsTo(LoanApplication::class);
    }

    /**
     * Relationship with the User who requested this revision.
     * Named "requester" to avoid collision with the "requested_by" FK column.
     */
    public function requester(): BelongsTo
    {
        return $this->belongsTo(User::class, 'requested_by');
    }

    /**
     * Relationship with the User who approved this revision.
     * Named "approver" to avoid collision with the "approved_by" FK column.
     */
    public function approver(): BelongsTo
    {
        return $this->belongsTo(User::class, 'approved_by');
    }

    /**
     * Relationship with the installments generated by this revision.
     */
    public function installments(): HasMany
    {
        return $this->hasMany(LoanInstallment::class, 'loan_revision_id');
    }

    /**
     * URL to the authenticated download endpoint for the supporting document,
     * never the raw storage path.
     */
    public function getDocumentUrlAttribute(): ?string
    {
        return $this->document ? url("/api/v1/loan-revisions/{$this->id}/document") : null;
    }
}
